# Generated by Django 4.2.3 on 2023-08-10 08:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('added', models.DateField(default=datetime.datetime(2023, 8, 10, 11, 50, 12, 145585))),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('birthday', models.DateField(default=datetime.datetime(2023, 8, 10, 11, 50, 12, 144586))),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creation_date', models.DateField(default=datetime.datetime(2023, 8, 10, 11, 50, 12, 145584))),
                ('goods_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dz_3_app.goods')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dz_3_app.user')),
            ],
        ),
    ]
